<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<Deterministic>false</Deterministic>
		<AssemblyTitle>LaneController</AssemblyTitle>
		<AssemblyVersion>1.0.*</AssemblyVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<LangVersion>preview</LangVersion>
		<AssemblyName>LaneController</AssemblyName>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>
	<Target Name="DeployToModDirectory" AfterTargets="Build">
		<PropertyGroup>
			<ModDirectory>$(LOCALAPPDATA)\Colossal Order\Cities_Skylines\Addons\Mods\$(ProjectName)\</ModDirectory>
		</PropertyGroup>
		<ItemGroup>
			<ModFiles Include="$(TargetDir)*.*" />
		</ItemGroup>
		<RemoveDir Directories="$(ModDirectory)" />
		<Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModDirectory)" />
	</Target>
	<ItemGroup>
	  <Compile Remove="libs\**" />
	  <EmbeddedResource Remove="libs\**" />
	  <None Remove="libs\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Resources\CloseButton\CloseButtonHovered.png" />
	  <None Remove="Resources\CloseButton\CloseButtonNormal.png" />
	  <None Remove="Resources\CloseButton\CloseButtonPressed.png" />
	  <None Remove="Resources\ColorPicker\ColorPickerBoard.png" />
	  <None Remove="Resources\ColorPicker\ColorPickerColor.png" />
	  <None Remove="Resources\ColorPicker\ColorPickerDisabled.png" />
	  <None Remove="Resources\ColorPicker\ColorPickerHovered.png" />
	  <None Remove="Resources\ColorPicker\ColorPickerNormal.png" />
	  <None Remove="Resources\directions.png" />
	  <None Remove="Resources\Empty.png" />
	  <None Remove="Resources\Field\FieldDisabled.png" />
	  <None Remove="Resources\Field\FieldDisabledLeft.png" />
	  <None Remove="Resources\Field\FieldDisabledMiddle.png" />
	  <None Remove="Resources\Field\FieldDisabledRight.png" />
	  <None Remove="Resources\Field\FieldFocused.png" />
	  <None Remove="Resources\Field\FieldFocusedLeft.png" />
	  <None Remove="Resources\Field\FieldFocusedMiddle.png" />
	  <None Remove="Resources\Field\FieldFocusedRight.png" />
	  <None Remove="Resources\Field\FieldHovered.png" />
	  <None Remove="Resources\Field\FieldHoveredLeft.png" />
	  <None Remove="Resources\Field\FieldHoveredMiddle.png" />
	  <None Remove="Resources\Field\FieldHoveredRight.png" />
	  <None Remove="Resources\Field\FieldNormal.png" />
	  <None Remove="Resources\Field\FieldNormalLeft.png" />
	  <None Remove="Resources\Field\FieldNormalMiddle.png" />
	  <None Remove="Resources\Field\FieldNormalRight.png" />
	  <None Remove="Resources\HeaderAdditionalButton.png" />
	  <None Remove="Resources\HeaderButtons\AddTemplateHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\ApplyHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\ApplyTemplateHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\BeetwenIntersectionsHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\CopyHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\CutHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\DuplicateHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\EdgeLinesHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\EditHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\NotSaveHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\PackageHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\PasteHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\ResetControlPointsHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\ResetHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\SaveHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\SetDefaultHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\UnsetDefaultHeaderButton.png" />
	  <None Remove="Resources\HeaderButtons\WholeStreetHeaderButton.png" />
	  <None Remove="Resources\HeaderHover.png" />
	  <None Remove="Resources\laneTypes.png" />
	  <None Remove="Resources\ListItem.png" />
	  <None Remove="Resources\OpacitySlider\OpacitySliderBoard.png" />
	  <None Remove="Resources\OpacitySlider\OpacitySliderColor.png" />
	  <None Remove="Resources\resize.png" />
	  <None Remove="Resources\Tabs\Tab.png" />
	  <None Remove="Resources\Tabs\TabDisabled.png" />
	  <None Remove="Resources\Tabs\TabFocused.png" />
	  <None Remove="Resources\Tabs\TabHover.png" />
	  <None Remove="Resources\Tabs\TabNormal.png" />
	  <None Remove="Resources\Tabs\TabPressed.png" />
	  <None Remove="Resources\TextFieldPanel.png" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="Resources\CloseButton\CloseButtonHovered.png" />
	  <EmbeddedResource Include="Resources\CloseButton\CloseButtonNormal.png" />
	  <EmbeddedResource Include="Resources\CloseButton\CloseButtonPressed.png" />
	  <EmbeddedResource Include="Resources\ColorPicker\ColorPickerBoard.png" />
	  <EmbeddedResource Include="Resources\ColorPicker\ColorPickerColor.png" />
	  <EmbeddedResource Include="Resources\ColorPicker\ColorPickerDisabled.png" />
	  <EmbeddedResource Include="Resources\ColorPicker\ColorPickerHovered.png" />
	  <EmbeddedResource Include="Resources\ColorPicker\ColorPickerNormal.png" />
	  <EmbeddedResource Include="Resources\directions.png" />
	  <EmbeddedResource Include="Resources\Empty.png" />
	  <EmbeddedResource Include="Resources\Field\FieldDisabled.png" />
	  <EmbeddedResource Include="Resources\Field\FieldDisabledLeft.png" />
	  <EmbeddedResource Include="Resources\Field\FieldDisabledMiddle.png" />
	  <EmbeddedResource Include="Resources\Field\FieldDisabledRight.png" />
	  <EmbeddedResource Include="Resources\Field\FieldFocused.png" />
	  <EmbeddedResource Include="Resources\Field\FieldFocusedLeft.png" />
	  <EmbeddedResource Include="Resources\Field\FieldFocusedMiddle.png" />
	  <EmbeddedResource Include="Resources\Field\FieldFocusedRight.png" />
	  <EmbeddedResource Include="Resources\Field\FieldHovered.png" />
	  <EmbeddedResource Include="Resources\Field\FieldHoveredLeft.png" />
	  <EmbeddedResource Include="Resources\Field\FieldHoveredMiddle.png" />
	  <EmbeddedResource Include="Resources\Field\FieldHoveredRight.png" />
	  <EmbeddedResource Include="Resources\Field\FieldNormal.png" />
	  <EmbeddedResource Include="Resources\Field\FieldNormalLeft.png" />
	  <EmbeddedResource Include="Resources\Field\FieldNormalMiddle.png" />
	  <EmbeddedResource Include="Resources\Field\FieldNormalRight.png" />
	  <EmbeddedResource Include="Resources\HeaderAdditionalButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\AddTemplateHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\ApplyHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\ApplyTemplateHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\BeetwenIntersectionsHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\CopyHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\CutHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\DuplicateHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\EdgeLinesHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\EditHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\NotSaveHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\PackageHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\PasteHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\ResetControlPointsHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\ResetHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\SaveHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\SetDefaultHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\UnsetDefaultHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderButtons\WholeStreetHeaderButton.png" />
	  <EmbeddedResource Include="Resources\HeaderHover.png" />
	  <EmbeddedResource Include="Resources\laneTypes.png" />
	  <EmbeddedResource Include="Resources\ListItem.png" />
	  <EmbeddedResource Include="Resources\OpacitySlider\OpacitySliderBoard.png" />
	  <EmbeddedResource Include="Resources\OpacitySlider\OpacitySliderColor.png" />
	  <EmbeddedResource Include="Resources\resize.png" />
	  <EmbeddedResource Include="Resources\Tabs\Tab.png" />
	  <EmbeddedResource Include="Resources\Tabs\TabDisabled.png" />
	  <EmbeddedResource Include="Resources\Tabs\TabFocused.png" />
	  <EmbeddedResource Include="Resources\Tabs\TabHover.png" />
	  <EmbeddedResource Include="Resources\Tabs\TabNormal.png" />
	  <EmbeddedResource Include="Resources\Tabs\TabPressed.png" />
	  <EmbeddedResource Include="Resources\TextFieldPanel.png" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="CitiesHarmony.API" Version="2.2.0" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ColossalManaged">
			<HintPath>..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed\ColossalManaged.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ICities">
			<HintPath>..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed\ICities.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="MoveItIntegration">
		  <HintPath>libs\MoveItIntegration.dll</HintPath>
		  <Private>False</Private>
		</Reference>
		<Reference Include="UnifiedUILib">
		  <HintPath>libs\UnifiedUILib.dll</HintPath>
		  <Private>True</Private>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>..\..\..\..\Program Files (x86)\Steam\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	<Target Name="ExcludeModdingReferences" AfterTargets="ResolveAssemblyReferences;CopyFilesToOutputDirectory">
		<ItemGroup>
			<!-- Remove specific DLLs from the copy list -->
			<ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' == 'PopsApiWrapper' or &#xD;&#xA;                 '%(Filename)' == 'Assembly-CSharp-firstpass' or &#xD;&#xA;                 '%(Filename)' == 'ICSharpCode.SharpZipLib'" />

			<!-- Identify and delete any leftover PDB files in the output directory -->
			<DeletePdbFiles Include="$(TargetDir)*.pdb" />
		</ItemGroup>

		<!-- This task actively deletes the PDBs after the build finishes -->
		<Delete Files="@(DeletePdbFiles)" />
	</Target>
</Project>